#ifndef NOTICE_HPP
#define NOTICE_HPP

enum class Notice {
    OPENING, 
    CLOSING,
    CAPACITY_REACHED,
    CAPACITY_AT_75,
    CAPACITY_SAFE,
    RAIN_ALERT,
    CLEAR_WEATHER,
    EVACUATION,
    RESUMING_OPERATION,
    TEMPORARILY_CLOSED,
    SCREEN_DOWN,
    STAGE_DOWN
};

#endif //NOTICE_HPP